### ISSUE TITLE
Upgrade net.openhft:chronicle to 3.4.3

### ISSUE THREAD

**Issue by artembilan** [spring-io/platform-foundation#2]
Otherwise we can't build Spring Integration against IO 2.0.

Thanks in advance!

**Comment by artembilan** [comment]
The fix:
````xml
<openhft-chronicle.version>3.4.3</openhft-chronicle.version>
<openhft-lang.version>6.6.4</openhft-lang.version>
````

**Comment by wilkinsona** [comment]
This should be opened against spring-io/platform. I've opened https://github.com/spring-io/platform/issues/208.
